apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.name }}
spec:
  acme:
    email: {{ .Values.email }}
    server: {{ .Values.server }}
    privateKeySecretRef:
      name: cluster-issuer-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingressClass }}
